/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagement;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Indian
 */
public class FineForm extends javax.swing.JFrame {
    Connection con = javaconnect.connectdb();
    PreparedStatement ps =null;
    JOptionPane j1;
    ResultSet rs = null;
    int totalbed = 400;
    /**
     * Creates new form RegistrationForm
     * @throws java.sql.SQLException
     */
    public FineForm() throws SQLException {
        j1 = new JOptionPane();
        initComponents();
        javaconnect.connectdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel30 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mon = new javax.swing.JComboBox<>();
        d = new javax.swing.JComboBox<>();
        yyyy = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        curyear = new javax.swing.JComboBox<>();
        sec = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        amo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        deg = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        roll = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        admn = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        deg1 = new javax.swing.JComboBox<>();
        c1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 198, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Degree & Branch");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 198, 36));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 36));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 140, 36));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Section");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 85, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Year");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 85, 36));

        name.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 273, 38));

        mon.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        mon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });
        getContentPane().add(mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 100, -1));

        d.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 80, -1));

        yyyy.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        yyyy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        getContentPane().add(yyyy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gender");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 198, 38));

        curyear.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        curyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year", "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        getContentPane().add(curyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 170, -1));

        sec.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        sec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Section", "A", "B", "C", "D", "E" }));
        getContentPane().add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 170, -1));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fine Category ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 190, 38));

        amo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        amo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amoActionPerformed(evt);
            }
        });
        getContentPane().add(amo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 150, 40));

        jLabel27.setFont(new java.awt.Font("Candara", 3, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Online fine amount payment");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 450, 50));

        deg.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        deg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Degree & Branch", "B.E - CSE", "B.E - ECE", "B.E - EEE", "B.E - MECH", "B.E - CIVIL", "B.E - BME", "B.TECH - BIO", "B.TECH - IT", "B.TECH - AIDS", "M.E - CSE" }));
        deg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degActionPerformed(evt);
            }
        });
        getContentPane().add(deg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 270, 40));

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Roll Number ");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 30));

        roll.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        getContentPane().add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 226, 270, 40));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admn Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 30));

        admn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(admn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 166, 270, 40));

        jToggleButton2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jToggleButton2.setText("Reset");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 760, 190, 50));

        male.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        female.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        jButton5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 760, 180, 50));

        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        ta.setRows(5);
        ta.setText("        *********************************\n           MSEC Online fine amount Payment\n       **********************************\n  \n\n    ");
        ta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taMouseClicked(evt);
            }
        });
        ta.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                taInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane2.setViewportView(ta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 520, 590));

        deg1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        deg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Degree & Branch", "B.E - CSE", "B.E - ECE", "B.E - EEE", "B.E - MECH", "B.E - CIVIL", "B.E - BME", "B.TECH - BIO", "B.TECH - IT", "B.TECH - AIDS", "M.E - CSE" }));
        deg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deg1ActionPerformed(evt);
            }
        });
        getContentPane().add(deg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 270, 40));

        c1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Broken - 200", "Room not locken - 100", "Going Trip - 500", "Illegal Activities - 1000", "Others - 500", " " }));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 270, 40));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please click on the bill to generate Bill...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 700, 440, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/187182.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void degActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            ps = con.prepareStatement("insert into finedata values(?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1,name.getText());
            ps.setString(2,admn.getText());
            ps.setString(3,roll.getText());
            String str1 = (String) d.getSelectedItem();
            String str2 = (String) mon.getSelectedItem();
           String str3 = (String) yyyy.getSelectedItem();
          StringBuilder strBuilder = new StringBuilder(40);
          strBuilder.append(str1);
          strBuilder.append("-");
         strBuilder.append(str2);
         strBuilder.append("-");
         strBuilder.append(str3);
         String concatString = strBuilder.toString();
            ps.setString(10,concatString);
            ps.setString(4, (String) curyear.getSelectedItem());
            ps.setString(6, (String) sec.getSelectedItem());
            ps.setString(5, (String) deg.getSelectedItem());
            if(male.isSelected())
                  ps.setString(7, male.getText());
            if(female.isSelected())
                  ps.setString(7, female.getText());
            ps.setString(8, (String) c1.getSelectedItem());
            ps.setString(9,amo.getText());
            String def="";
            if("".equals(name.getText()) | ("".equals(male.getText())& "".equals(female.getText()))|"".equals(admn.getText()) |"".equals(roll.getText())|"".equals(amo.getText())|"0".equals(curyear.getSelectedIndex())|"0".equals(sec.getSelectedIndex())|"0".equals(deg.getSelectedIndex())|"0".equals(d.getSelectedIndex())|"0".equals(mon.getSelectedIndex())|"0".equals(yyyy.getSelectedIndex())|"0".equals(c1.getSelectedIndex()))    
            {
                j1.setFont(new Font("Candara", Font.BOLD, 40));
                 JOptionPane.showMessageDialog(null,"Please fill all the Data");
            }
            else
            {
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Successfully Payed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FineForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        String def = "";
            name.setText(def);
            admn.setText(def);
            roll.setText(def);
            d.setSelectedIndex(0);
            mon.setSelectedIndex(0);
            yyyy.setSelectedIndex(0);
            curyear.setSelectedIndex(0);
            sec.setSelectedIndex(0);
            deg.setSelectedIndex(0);
            male.setSelected(false);
            female.setSelected(false);
            c1.setSelectedIndex(0);
            amo.setText(def);
            ta.setText(def);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monActionPerformed

    private void amoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_amoActionPerformed

    private void deg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deg1ActionPerformed

    private void taInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_taInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_taInputMethodTextChanged

    private void taMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taMouseClicked
        // TODO add your handling code here:
        String data = "        ************************************\n            MSEC Online Fine Amount Payment Bill\n         ************************************\n\n";
                String data1 = "  Name : " + name.getText() + "\n\n" + "  Admission Number : " + admn.getText() + "\n\n"+"  Roll Number : " + roll.getText() + "\n\n  Degree and Branch : " + deg.getSelectedItem() + "\n\n  Year : "+ jLabel10.getText();
                String data2 = "\n\n  Section : " + sec.getSelectedItem();
                String data3 = "\n\n  Fine Category : " +  c1.getSelectedItem();
                String data4 = "\n\n  Amount : " + amo.getText();
                ta.setText(data + data1 + data2 + data3 + data4);
                ta.setEditable(false);
    }//GEN-LAST:event_taMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FineForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FineForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admn;
    private javax.swing.JTextField amo;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> curyear;
    private javax.swing.JComboBox<String> d;
    private javax.swing.JComboBox<String> deg;
    private javax.swing.JComboBox<String> deg1;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> mon;
    private javax.swing.JTextField name;
    private javax.swing.JTextField roll;
    private javax.swing.JComboBox<String> sec;
    private javax.swing.JTextArea ta;
    private javax.swing.JComboBox<String> yyyy;
    // End of variables declaration//GEN-END:variables
}
