/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagement;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.sql.Statement;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Indian
 */
public class RegistrationForm extends javax.swing.JFrame {
    Connection con = javaconnect.connectdb();
    PreparedStatement ps =null;
    JOptionPane j1;
    ResultSet rs = null;
    int totalbed = 400;
    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() throws SQLException {
        j1 = new JOptionPane();
        initComponents();
        javaconnect.connectdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mon = new javax.swing.JComboBox<>();
        d = new javax.swing.JComboBox<>();
        yyyy = new javax.swing.JComboBox<>();
        blood = new javax.swing.JTextField();
        host = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dist = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        sta = new javax.swing.JTextField();
        phostu = new javax.swing.JTextField();
        curyear = new javax.swing.JComboBox<>();
        sec = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        fatname = new javax.swing.JTextField();
        fatocu = new javax.swing.JTextField();
        fatpho = new javax.swing.JTextField();
        motname = new javax.swing.JTextField();
        motocu = new javax.swing.JTextField();
        motpho = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        messv = new javax.swing.JRadioButton();
        messnv = new javax.swing.JRadioButton();
        room = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        deg = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        roll = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        admn = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personal Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, 300, 40));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 198, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Degree & Branch");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 198, 36));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 36));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Blood Group");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 830, 198, 36));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hostel Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, 140, 36));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mess");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 770, 120, 36));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Section");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 183, 85, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Year");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 85, 36));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 193, 45));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Phone Number ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 190, 38));

        jLabel13.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Parent Details");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 270, 35));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Father Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 140, 39));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mother Name");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 150, 37));

        name.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 273, 38));

        mon.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        mon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });
        getContentPane().add(mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 100, -1));

        d.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 80, -1));

        yyyy.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        yyyy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        getContentPane().add(yyyy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        blood.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodActionPerformed(evt);
            }
        });
        getContentPane().add(blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 830, 280, 39));

        host.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        host.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Hostel", "Krishna Hostel", "Kavery Hostel", "Brahmaputra Hostel", "Godavari Hostel", "Narmadha Hostel", "Yamuna Hostel", "Ganga Hostel", "Mahanadhi Hostel" }));
        host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostActionPerformed(evt);
            }
        });
        getContentPane().add(host, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 710, 220, 40));

        add.setColumns(20);
        add.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        add.setRows(5);
        jScrollPane1.setViewportView(add);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 368, 110));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gender");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 198, 38));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("District ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 190, 37));

        dist.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        dist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distActionPerformed(evt);
            }
        });
        getContentPane().add(dist, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 279, 40));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("State");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 193, 36));

        sta.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(sta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 279, 43));

        phostu.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        phostu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phostuActionPerformed(evt);
            }
        });
        getContentPane().add(phostu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 700, 279, 40));

        curyear.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        curyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year", "I Year", "II Year", "III Year", "IV Year" }));
        getContentPane().add(curyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 130, 170, -1));

        sec.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        sec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Section", "A", "B", "C", "D", "E" }));
        getContentPane().add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 180, 170, -1));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Mail ID");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 190, 38));

        mail.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 760, 279, 38));

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Occupation");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 140, 30));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Phone No.");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 130, -1));

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Occupation");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 140, -1));

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Phone No.");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 110, 30));

        jLabel26.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Hostel Details");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 220, 30));

        fatname.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        fatname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatnameActionPerformed(evt);
            }
        });
        getContentPane().add(fatname, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 220, 40));

        fatocu.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(fatocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 220, 40));

        fatpho.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(fatpho, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 220, 40));

        motname.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(motname, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 220, 40));

        motocu.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(motocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, 220, 40));

        motpho.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(motpho, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 220, 40));

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Room Number ");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 830, 160, 30));

        messv.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        messv.setForeground(new java.awt.Color(255, 255, 255));
        messv.setText("Veg");
        messv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messvActionPerformed(evt);
            }
        });
        getContentPane().add(messv, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 770, 80, -1));

        messnv.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        messnv.setForeground(new java.awt.Color(255, 255, 255));
        messnv.setText("Non-Veg");
        messnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messnvActionPerformed(evt);
            }
        });
        getContentPane().add(messnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 770, 130, -1));

        room.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomActionPerformed(evt);
            }
        });
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 820, 150, 40));

        jLabel27.setFont(new java.awt.Font("Candara", 3, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Hostel Registration Form");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 400, 50));

        deg.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        deg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Degree & Branch", "B.E - CSE", "B.E - ECE", "B.E - EEE", "B.E - MECH", "B.E - CIVIL", "B.E - BME", "B.TECH - BIO", "B.TECH - IT", "B.TECH - AIDS", "M.E - CSE" }));
        deg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degActionPerformed(evt);
            }
        });
        getContentPane().add(deg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 270, 40));

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Roll Number ");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 30));

        roll.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        getContentPane().add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 226, 270, 40));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admn Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 30));

        admn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getContentPane().add(admn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 166, 270, 40));

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jToggleButton2.setText("Reset");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 910, 190, 50));

        male.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        female.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        jButton3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton3.setText("Check Bed Availability");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, -1, 110));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 910, 180, 50));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/658353.jpg"))); // NOI18N
        jLabel31.setText("jLabel31");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void bloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodActionPerformed

    private void hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostActionPerformed

    private void fatnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatnameActionPerformed

    private void roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomActionPerformed

    private void distActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollActionPerformed

    private void messvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messvActionPerformed

    private void messnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messnvActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try {
            // TODO add your handling code here:
            Statement stmt = con.createStatement();
      //Query to get the number of rows in a table
      String query = "select count(*) from student";
      //Executing the query
      rs = stmt.executeQuery(query);
      //Retrieving the result
      rs.next();
      int bed = rs.getInt(1);
      int beds = totalbed -bed;
            j1.showMessageDialog(null,"Available Beds : "+beds);           
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void degActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degActionPerformed

    private void phostuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phostuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phostuActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            ps = con.prepareStatement("insert into student values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1,name.getText());
            ps.setString(2,admn.getText());
            ps.setString(3,roll.getText());
            String str1 = (String) d.getSelectedItem();
            String str2 = (String) mon.getSelectedItem();
           String str3 = (String) yyyy.getSelectedItem();
          StringBuilder strBuilder = new StringBuilder(40);
          strBuilder.append(str1);
          strBuilder.append("-");
         strBuilder.append(str2);
         strBuilder.append("-");
         strBuilder.append(str3);
         String concatString = strBuilder.toString();
            ps.setString(23,concatString);
            ps.setString(4, (String) curyear.getSelectedItem());
            ps.setString(5, (String) sec.getSelectedItem());
            ps.setString(6, (String) deg.getSelectedItem());
            ps.setString(7,(String) mon.getSelectedItem());
            if(male.isSelected())
                ps.setString(7, male.getText());
            if(female.isSelected())
                ps.setString(7, female.getText());
            ps.setString(8,add.getText());
            ps.setString(9,sta.getText());
            ps.setString(10,dist.getText());
            ps.setString(11,phostu.getText());
            ps.setString(12,mail.getText());
            ps.setString(13,blood.getText());
            ps.setString(14,fatname.getText());
            ps.setString(15,fatocu.getText());
            ps.setString(16,fatpho.getText());
            ps.setString(17,motname.getText());
            ps.setString(18,motocu.getText());
            ps.setString(19,motpho.getText());
            ps.setString(20, (String) host.getSelectedItem());
            if(messv.isSelected())
                 ps.setString(21, messv.getText());
            if(messnv.isSelected())
                 ps.setString(21, messnv.getText());
            ps.setString(22,room.getText());
            String def="";
            if("".equals(name.getText()) | ("".equals(male.getText())& "".equals(female.getText()))|("".equals(messv.getText())&"".equals(messnv.getText()))|"".equals(admn.getText()) |"".equals(roll.getText())|"".equals(add.getText())|"".equals(dist.getText())|"".equals(sta.getText())|"".equals(phostu.getText())|"".equals(mail.getText())|"".equals(blood.getText())|"".equals(fatname.getText())|"".equals(fatocu.getText())|"".equals(fatpho.getText())|"".equals(motname.getText())|"".equals(motocu.getText())|"".equals(motpho.getText())|"".equals(room.getText())|"0".equals(curyear.getSelectedIndex())|"0".equals(sec.getSelectedIndex())|"0".equals(deg.getSelectedIndex())|"0".equals(d.getSelectedIndex())|"0".equals(mon.getSelectedIndex())|"0".equals(yyyy.getSelectedIndex())|"0".equals(host.getSelectedIndex()))    
            {
                j1.setFont(new Font("Candara", Font.BOLD, 40));
                 JOptionPane.showMessageDialog(null,"Please fill all the Data");
            }
            else
            {
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Successfully Alloted");
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        String def = "";
            name.setText(def);
            admn.setText(def);
            roll.setText(def);
            curyear.setSelectedIndex(0);
            sec.setSelectedIndex(0);
            deg.setSelectedIndex(0);
            male.setSelected(false);
            female.setSelected(false);
            add.setText(def);
            d.setSelectedIndex(0);
            mon.setSelectedIndex(0);
            yyyy.setSelectedIndex(0);
            sta.setText(def);
            dist.setText(def);
            phostu.setText(def);
            mail.setText(def);
            blood.setText(def);
            fatname.setText(def);
            fatocu.setText(def);
            fatpho.setText(def);
            motname.setText(def);
            motocu.setText(def);
            motpho.setText(def);
            host.setSelectedIndex(0);
            messv.setSelected(false);
            messnv.setSelected(false);
            room.setText(def);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegistrationForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private javax.swing.JTextField admn;
    private javax.swing.JTextField blood;
    private javax.swing.JComboBox<String> curyear;
    private javax.swing.JComboBox<String> d;
    private javax.swing.JComboBox<String> deg;
    private javax.swing.JTextField dist;
    private javax.swing.JTextField fatname;
    private javax.swing.JTextField fatocu;
    private javax.swing.JTextField fatpho;
    private javax.swing.JRadioButton female;
    private javax.swing.JComboBox<String> host;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField mail;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton messnv;
    private javax.swing.JRadioButton messv;
    private javax.swing.JComboBox<String> mon;
    private javax.swing.JTextField motname;
    private javax.swing.JTextField motocu;
    private javax.swing.JTextField motpho;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phostu;
    private javax.swing.JTextField roll;
    private javax.swing.JTextField room;
    private javax.swing.JComboBox<String> sec;
    private javax.swing.JTextField sta;
    private javax.swing.JComboBox<String> yyyy;
    // End of variables declaration//GEN-END:variables
}
